services:
  app-ss: # создание контейнера с питоновским приложением
    build: 
      context: . # сборка образа с приложением
    ports: # доступ к приложению по порту
      - 8000:8000
    env_file: # создание файла с переменными приложения
      - app.env
    depends_on: # создание зависимости, по которому в первую очередь должен запуститься контейнер с базой данных
      db-ss:
        condition: service_healthy
    volumes: # создание волюма и монтирование его в директорию с пользовательскими картинками
      - app-ss-uploads:/app/media/uploads

  db-ss: 
    image: postgres:16.1-alpine3.18
    volumes: # создание волюма и монтирование его в директорию с файлами БД
      - db-ss-data:/var/lib/postgresql/data
    env_file: # создание файла с переменными приложения
      - db.env
    expose: # открытие порта для соединения приложения питона с БД
      - 5432
    healthcheck: # проверка запуска контейнера с БД, и готовность принимать запросы
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes: # описание всех используемых волюмов
  db-ss-data:
  app-ss-uploads:
